language: ruby
rvm: 2.1
bundler_args: "--without deployment development"
script: rake travis:deploy
env:
  global:
    secure: suCRsJSwNJKQlSdVWQ32HR6NbSu/MXXMwf1pCY7OKVT+u0wgX9sU2rejgjXP8yXLLi2VKe/ZKCKTCQxorLIDDZQxglbcwqnNTAf40pcTJakfSN+9ITlR4oTcrzobCMDyrhPvOaQcFiio9tDoRzJhBSffLcGjo/Y17JEz0VG7QmI=
