language: ruby
rvm: 2.3.0
sudo: false
bundler_args: --without development
script: rake travis:deploy
env:
  global:
  - secure: jZtIcNKAOyxLEXXM7NvGSeasdqxmWKWyunhH6uBT00i25PpV7HZB8M5NWR6L4+Z3xBrdcsPdEJ9eaBFFnDXBzg9eW1MI384+1n3j1+Y8+DxpHaVn/Jt/37oLOoVCxRv0t5SVi+bEEoZWgl7O9k9iu4xgGnI1vGebw2WJdHtVch0=
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

notifications:
  slack:
    secure: MaU1NTfW2VaS4hzfHRghJ1u1yFKFhlB4yKuvXMq1HeB4GEcKtZ5HQ2lF9s2oYYHMN7L7YZHKRtV8b4XwzrRk8euA1N1+lePuWeE3hw4VOBMhVBPbDsiC1DX08uH/KWHGSFV/Ep3q2RHpjIwoRVvwAB0XLQNaDy7pkhL7Z/hEfh0=
