language: ruby
rvm: 2.3.0
sudo: false
bundler_args: --without development
script: rake travis:deploy
env:
  global:
  - secure: suCRsJSwNJKQlSdVWQ32HR6NbSu/MXXMwf1pCY7OKVT+u0wgX9sU2rejgjXP8yXLLi2VKe/ZKCKTCQxorLIDDZQxglbcwqnNTAf40pcTJakfSN+9ITlR4oTcrzobCMDyrhPvOaQcFiio9tDoRzJhBSffLcGjo/Y17JEz0VG7QmI=
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

notifications:
  slack:
    secure: MaU1NTfW2VaS4hzfHRghJ1u1yFKFhlB4yKuvXMq1HeB4GEcKtZ5HQ2lF9s2oYYHMN7L7YZHKRtV8b4XwzrRk8euA1N1+lePuWeE3hw4VOBMhVBPbDsiC1DX08uH/KWHGSFV/Ep3q2RHpjIwoRVvwAB0XLQNaDy7pkhL7Z/hEfh0=
