text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false

prune:
  auto_prune: true
  exclude: ['.git', '.hg', '.svn']

data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
  -
    type: static
    items_root: /assets/

base_url: http://www.thinreports.org

