# Thinreports Site Configuration
---
title: オープンソース PDF 帳票ツール for Ruby, Rails

version: 0.9.1

editor:
  version: 0.9.1
  released_at: "2016-07-25"
  announcement: /news/2016/07/thinreports-editor-0_9_1-released/
generator:
  version: 0.9.1
  released_at: "2016-06-03"
  announcement: /news/2016/06/thinreports-generator-0_9_1-released/

related_url:
  chrome_web_store: https://chrome.google.com/webstore/detail/thinreports-editor/cdlcnnandndjkbbdcbpnjoimphmifkfn
  rubygems: https://rubygems.org/gems/thinreports
  discussion_group: "https://groups.google.com/forum/#!forum/thinreports"
