# Thinreports Site Configuration
---
title: オープンソース PDF 帳票ツール for Ruby, Rails

version: 0.8.2

editor:
  version: 0.8.2
  released_at: "2015-06-23"
  announcement: /news/2015/06/thinreports-editor-0_8_2-released/
generator:
  version: 0.8.1
  released_at: "2015-07-23"
  announcement: /news/2015/07/thinreports-generator-0_8_1-released/

related_url:
  chrome_web_store: https://chrome.google.com/webstore/detail/thinreports-editor/cdlcnnandndjkbbdcbpnjoimphmifkfn
  rubygems: https://rubygems.org/gems/thinreports
  discussion_group: "https://groups.google.com/forum/#!forum/thinreports"
  sourceforge: http://sourceforge.net/projects/thinreports/files
