# Thinreports Site Configuration
---
title: オープンソース PDF 帳票ツール for Ruby, Rails

version: 0.9.0

editor:
  version: 0.9.0
  released_at: "2016-05-28"
  announcement: /news/2016/05/thinreports-0_9_0-released/
generator:
  version: 0.9.0
  released_at: "2016-05-28"
  announcement: /news/2016/05/thinreports-0_9_0-released/

related_url:
  chrome_web_store: https://chrome.google.com/webstore/detail/thinreports-editor/cdlcnnandndjkbbdcbpnjoimphmifkfn
  rubygems: https://rubygems.org/gems/thinreports
  discussion_group: "https://groups.google.com/forum/#!forum/thinreports"
  sourceforge: http://sourceforge.net/projects/thinreports/files
