# Thinreports Site Configuration
---
title: オープンソース PDF 帳票ツール for Ruby, Rails

version: 0.10.0

editor:
  version: 0.10.0
  released_at: "2017-09-01"
  announcement: /news/2017/09/thinreports-editor-0_10_0-released/
generator:
  version: 0.10.0
  released_at: "2017-05-10"
  announcement: /news/2017/05/thinreports-generator-0_10_0-released/

related_url:
  editor_releases: https://github.com/thinreports/thinreports-editor/releases
  rubygems: https://rubygems.org/gems/thinreports
  discussion_group: "https://groups.google.com/forum/#!forum/thinreports"
  # Deptecated
  chrome_web_store: https://chrome.google.com/webstore/detail/thinreports-editor/cdlcnnandndjkbbdcbpnjoimphmifkfn
