# Thinreports Site Configuration
---
title: オープンソース PDF 帳票ツール for Ruby, Rails

version: 0.12.0

editor:
  version: 0.12.0
  released_at: "2021-01-16"
  announcement: /news/2021/01/thinreports-v0_12_0-released/
generator:
  version: 0.12.0
  released_at: "2021-01-16"
  announcement: /news/2021/01/thinreports-v0_12_0-released/

related_url:
  editor_releases: https://github.com/thinreports/thinreports-editor/releases
  rubygems: https://rubygems.org/gems/thinreports
  github_discussions: "https://github.com/thinreports/thinreports/discussions"
  # Deptecated
  chrome_web_store: https://chrome.google.com/webstore/detail/thinreports-editor/cdlcnnandndjkbbdcbpnjoimphmifkfn
